apiVersion: apps/v1
kind: Deployment
metadata:
  name: sage-v-server
spec:
  selector:
    matchLabels:
      app: sage-v-server
  template:
    metadata:
      labels:
        app: sage-v-server
    spec:
      containers:
        - name: sage-v-server
          image: sage-vcr.azurecr.io/sage-vserver
          ports:
            - containerPort: 8000
          imagePullPolicy: Always

          ENV:
            - name: AZURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_ID
                  name: sage-v-secret

            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: AZURE_CLIENT_SECRET
                  name: sage-v-secret

            - name: AZURE_TENANT_ID
              valueFrom:
                secretKeyRef:
                  key: AZURE_TENANT_ID
                  name: sage-v-secret

            - name: BLOB_STORE
              valueFrom:
                secretKeyRef:
                  key: BLOB_STORE
                  name: sage-v-secret

            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: JWT_SECRET_KEY
                  name: sage-v-secret

            - name: APP_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: APP_DB_NAME
                  name: sage-v-secret

            - name: LOG_DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: LOG_DB_CONNECTION_STRING
                  name: sage-v-secret

            - name: LOG_DB_NAME
              valueFrom:
                secretKeyRef:
                  key: LOG_DB_NAME
                  name: sage-v-secret

            - name: APP_DB_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  key: APP_DB_CONNECTION_STRING
                  name: sage-v-secret

            - name: CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  key: CELERY_BROKER_URL
                  name: sage-v-secret

            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  key: REDIS_HOST
                  name: sage-v-secret

            - name: REDIS_PORT
              valueFrom:
                secretKeyRef:
                  key: REDIS_PORT
                  name: sage-v-secret

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: REDIS_PASSWORD
                  name: sage-v-secret

            - name: REDIS_DB
              valueFrom:
                secretKeyRef:
                  key: REDIS_DB
                  name: sage-v-secret

            - name: HEARTBEAT_API_KEY
              valueFrom:
                secretKeyRef:
                  key: HEARTBEAT_API_KEY
                  name: sage-v-secret

            - name: LOG_REQUEST_RESPONSE_DATA_FLAG
              valueFrom:
                secretKeyRef:
                  key: LOG_REQUEST_RESPONSE_DATA_FLAG
                  name: sage-v-secret

            - name: RABBITMQ_DEFAULT_USER
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_DEFAULT_USER
                  name: sage-v-secret

            - name: RABBITMQ_DEFAULT_PASS
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_DEFAULT_PASS
                  name: sage-v-secret

            - name: RABBITMQ_DEFAULT_VHOST
              valueFrom:
                secretKeyRef:
                  key: RABBITMQ_DEFAULT_VHOST
                  name: sage-v-secret

            - name: PROMETHEUS_URL
              valueFrom:
                secretKeyRef:
                  key: PROMETHEUS_URL
                  name: sage-v-secret

            - name: PROM_AGG_GATEWAY_USERNAME
              valueFrom:
                secretKeyRef:
                  key: PROM_AGG_GATEWAY_USERNAME
                  name: sage-v-secret

            - name: PROM_AGG_GATEWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PROM_AGG_GATEWAY_PASSWORD
                  name: sage-v-secret

            - name: NEXT_PUBLIC_BACKEND_API_URL
              valueFrom:
                secretKeyRef:
                  key: NEXT_PUBLIC_BACKEND_API_URL
                  name: sage-v-secret

            - name: FRONTEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: sage-v-configmap
                  key: FRONTEND_PORT

            - name: BACKEND_PORT
              valueFrom:
                configMapKeyRef:
                  name: sage-v-configmap
                  key: BACKEND_PORT

            - name: BACKEND_WORKERS
              valueFrom:
                configMapKeyRef:
                  name: sage-v-configmap
                  key: BACKEND_WORKERS

            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: sage-v-configmap
                  key: ENV

            - name: VAD_DIR
              valueFrom:
                configMapKeyRef:
                  name: sage-v-configmap
                  key: VAD_DIR

            - name: MIGRATION_ACTION
              valueFrom:
                configMapKeyRef:
                  name: sage-v-configmap
                  key: MIGRATION_ACTION

          command:
            - "uvicorn"
            - "main:app"
            - "--workers"
            - "$(BACKEND_WORKERS)"
            - "--port"
            - "$(BACKEND_PORT)"
            - "--host"
            - "0.0.0.0"
            - "--proxy-headers"

      volumes:
        - name: app-data
