{
 "title": "Sage V Inference Request Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "apiKeyName", "label": "API Key Name", "query": ".*" },
   { "name": "userId", "label": "User Id", "query": ".*" },
   { "name": "inferenceServiceId", "label": "Inference Service Id", "query": ".*" },
   { "name": "taskType", "label": "Task Type", "query": ".*" },
   { "name": "sourceLanguage", "label": "Source Language", "query": ".*" },
   { "name": "targetLanguage", "label": "Target Language", "query": ".*" }
  ]
 },
 "panels": [
  {
   "title": "Requests Per Second",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(dhruva_inference_request_total{inference_service=~\"$inferenceServiceId\", user_id=~\"$userId\", api_key_name=~\"$apiKeyName\", task_type=~\"$taskType\", source_language=~\"$sourceLanguage\", target_language=~\"$targetLanguage\"}[5m])) OR vector(0)"
    }
   ]
  },
  {
   "title": "Request Processing Time",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(dhruva_inference_request_duration_seconds_bucket{inference_service=~\"$inferenceServiceId\", user_id=~\"$userId\", api_key_name=~\"$apiKeyName\", task_type=~\"$taskType\", source_language=~\"$sourceLanguage\", target_language=~\"$targetLanguage\"}[5m]) > 0) by (le)) or vector(0)"
    }
   ]
  },
  {
   "title": "Requests Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dhruva_inference_request_total{inference_service=~\"$inferenceServiceId\", user_id=~\"$userId\", api_key_name=~\"$apiKeyName\", task_type=~\"$taskType\", source_language=~\"$sourceLanguage\", target_language=~\"$targetLanguage\"}[$__range])) OR vector(0)",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Requests Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(dhruva_inference_request_total{inference_service=~\"$inferenceServiceId\", user_id=~\"$userId\", api_key_name=~\"$apiKeyName\", task_type=~\"$taskType\", source_language=~\"$sourceLanguage\", target_language=~\"$targetLanguage\"}[5m])) OR vector(0)",
     "legendFormat": "Rate"
    }
   ]
  },
  {
   "title": "Requests Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(dhruva_inference_request_duration_seconds_bucket{inference_service=~\"$inferenceServiceId\", user_id=~\"$userId\", api_key_name=~\"$apiKeyName\", task_type=~\"$taskType\", source_language=~\"$sourceLanguage\", target_language=~\"$targetLanguage\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(dhruva_inference_request_duration_seconds_bucket{inference_service=~\"$inferenceServiceId\", user_id=~\"$userId\", api_key_name=~\"$apiKeyName\", task_type=~\"$taskType\", source_language=~\"$sourceLanguage\", target_language=~\"$targetLanguage\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(dhruva_inference_request_duration_seconds_bucket{inference_service=~\"$inferenceServiceId\", user_id=~\"$userId\", api_key_name=~\"$apiKeyName\", task_type=~\"$taskType\", source_language=~\"$sourceLanguage\", target_language=~\"$targetLanguage\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(dhruva_inference_request_duration_seconds_bucket{inference_service=~\"$inferenceServiceId\", user_id=~\"$userId\", api_key_name=~\"$apiKeyName\", task_type=~\"$taskType\", source_language=~\"$sourceLanguage\", target_language=~\"$targetLanguage\"}[5m])) by (le)) OR vector(0)",
     "legendFormat": "0.1"
    }
   ]
  }
 ]
}